/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Product;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author kashi
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    Product product;
    public ViewJPanel(Product product) {
        initComponents();
        
        this.product = product;
        displayproduct();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtaddress1 = new javax.swing.JTextField();
        txtaddress2 = new javax.swing.JTextField();
        txtcontact = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtfax = new javax.swing.JTextField();
        txtssn = new javax.swing.JTextField();
        txtmrn = new javax.swing.JTextField();
        txthealth = new javax.swing.JTextField();
        txtban = new javax.swing.JTextField();
        txtlicense = new javax.swing.JTextField();
        txtvehicle = new javax.swing.JTextField();
        txtdevice = new javax.swing.JTextField();
        txtlinkedin = new javax.swing.JTextField();
        txtips = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtuin = new javax.swing.JTextPane();
        jLabel17 = new javax.swing.JLabel();
        txtphoto = new javax.swing.JLabel();
        imgprv = new javax.swing.JLabel();
        txtdob = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Profile:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Name:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Address:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Contact :");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("FAX Number:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Email:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Social Security Number:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Medical Record Number:");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Date of Birth:");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Health Plan Beneficiary Number:");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Bank Account Number:");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Certificate/ License Number:");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel13.setText("Vehicle Identifiers:");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel14.setText("Device Identifiers:");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel15.setText("Internet protocol Addresses:");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel16.setText("LinkedIn:");

        txtcontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcontactKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcontactKeyReleased(evt);
            }
        });

        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtemailKeyPressed(evt);
            }
        });

        txtfax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfaxKeyPressed(evt);
            }
        });

        txtssn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtssnKeyPressed(evt);
            }
        });

        txtmrn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmrnKeyPressed(evt);
            }
        });

        txthealth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txthealthKeyPressed(evt);
            }
        });

        txtban.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbanKeyPressed(evt);
            }
        });

        txtlicense.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtlicenseKeyPressed(evt);
            }
        });

        txtvehicle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtvehicleKeyPressed(evt);
            }
        });

        txtdevice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdeviceKeyPressed(evt);
            }
        });

        txtlinkedin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtlinkedinKeyPressed(evt);
            }
        });

        txtips.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtipsKeyPressed(evt);
            }
        });

        txtuin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtuinKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtuin);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel17.setText("Unique Identification Number:");

        txtphoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtphoto.setText("Image:");

        imgprv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                imgprvKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtlinkedin)
                    .addComponent(txtdevice)
                    .addComponent(txtvehicle)
                    .addComponent(txtlicense)
                    .addComponent(txtban)
                    .addComponent(txthealth)
                    .addComponent(txtmrn)
                    .addComponent(txtssn)
                    .addComponent(txtemail)
                    .addComponent(txtfax)
                    .addComponent(txtcontact)
                    .addComponent(txtdob)
                    .addComponent(txtaddress2)
                    .addComponent(txtaddress1)
                    .addComponent(txtaddress)
                    .addComponent(txtname)
                    .addComponent(txtips, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgprv, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtphoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtaddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtaddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtfax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtmrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txthealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtlicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtvehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtdevice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtlinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(imgprv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtips, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addGap(250, 250, 250))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtuinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuinKeyPressed
        // TODO add your handling code here:
        String uin = txtuin.getText();
        int length = uin.length();

        char c = evt.getKeyChar();

        if (evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            if (length<15)
            {
                txtuin.setEditable(true);
            }
            else
            {
                txtuin.setEditable(false);
            }
        }
        else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                txtuin.setEditable(true);
            }
            else
            {
                txtuin.setEditable(false);
            }

        }
    }//GEN-LAST:event_txtuinKeyPressed

    private void txtipsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtipsKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtipsKeyPressed

    private void txtlinkedinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlinkedinKeyPressed
        // TODO add your handling code here:
        /*if(!txtlinkedin.getText().isEmpty()){
            String regex = "((http(s?)://)*([a-zA-Z0-9\-])*\.|[linkedin])[linkedin/~\-]+\.[a-zA-Z0-9/~\-_,&=\?\.;]+[^\.,\s<]')";
            if(txtlinkedin.getText().matches(regex)){
                product.setlinkedin(txtlinkedin.getText());
                */
    }//GEN-LAST:event_txtlinkedinKeyPressed

    private void txtdeviceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdeviceKeyPressed
        // TODO add your handling code here:
        String device = txtdevice.getText();
        int length = device.length();

        char c = evt.getKeyChar();

        if (evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            if (length<40)
            {
                txtdevice.setEditable(true);
            }
            else
            {
                txtdevice.setEditable(false);
            }
        }
        else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                txtdevice.setEditable(true);
            }
            else
            {
                txtdevice.setEditable(false);
            }

        }
    }//GEN-LAST:event_txtdeviceKeyPressed

    private void txtvehicleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvehicleKeyPressed
        // TODO add your handling code here:
        /* if(!txtvehicle.getText().isEmpty()){
            String regex = "/^(?<wmi>[A-HJ-NPR-Z\d]{3})(?<vds>[A-HJ-NPR-Z\d]{5})(?<check>[\dX])(?<vis>(?<year>[A-HJ-NPR-Z\d])(?<plant>[A-HJ-NPR-Z\d])(?<seq>[A-HJ-NPR-Z\d]{6}))$/";
            if(txtvehicle.getText().matches(regex)){
                product.setVehicleidentifier(txtvehicle.getText());
            }
        }*/
    }//GEN-LAST:event_txtvehicleKeyPressed

    private void txtlicenseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlicenseKeyPressed
        // TODO add your handling code here:
        if(!txtlicense.getText().isEmpty()){
            String regex = "[A-Z]{1}[0-9]{9}";
            if(txtlicense.getText().matches(regex)){
                product.setLicenseNumber(txtlicense.getText());
            }
        }
    }//GEN-LAST:event_txtlicenseKeyPressed

    private void txtbanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbanKeyPressed
        // TODO add your handling code here:
        String bank = txtban.getText();
        int length = bank.length();

        char c = evt.getKeyChar();

        if (evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            if (length<12)
            {
                txtban.setEditable(true);
            }
            else
            {
                txtban.setEditable(false);
            }
        }
        else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                txtban.setEditable(true);
            }
            else
            {
                txtban.setEditable(false);
            }

        }
    }//GEN-LAST:event_txtbanKeyPressed

    private void txthealthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthealthKeyPressed
        // TODO add your handling code here:
        String health = txthealth.getText();
        int length = health.length();

        char c = evt.getKeyChar();

        if (evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            if (length<12)
            {
                txthealth.setEditable(true);
            }
            else
            {
                txthealth.setEditable(false);
            }
        }
        else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                txthealth.setEditable(true);
            }
            else
            {
                txthealth.setEditable(false);
            }

        }
    }//GEN-LAST:event_txthealthKeyPressed

    private void txtmrnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmrnKeyPressed
        // TODO add your handling code here:
        String mrn = txtmrn.getText();
        int length = mrn.length();

        char c = evt.getKeyChar();

        if (evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            if (length<6)
            {
                txtmrn.setEditable(true);
            }
            else
            {
                txtmrn.setEditable(false);
            }
        }
        else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                txtmrn.setEditable(true);
            }
            else
            {
                txtmrn.setEditable(false);
            }

        }
    }//GEN-LAST:event_txtmrnKeyPressed

    private void txtssnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtssnKeyPressed
        // TODO add your handling code here:
        String social = txtssn.getText();
        int length = social.length();

        char c = evt.getKeyChar();

        if (evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            if (length<9)
            {
                txtssn.setEditable(true);
            }
            else
            {
                txtssn.setEditable(false);
            }
        }
        else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                txtssn.setEditable(true);
            }
            else
            {
                txtssn.setEditable(false);
            }

        }
    }//GEN-LAST:event_txtssnKeyPressed

    private void txtfaxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfaxKeyPressed
        // TODO add your handling code here:
        String fax = txtfax.getText();
        int length = fax.length();

        char c = evt.getKeyChar();

        if (evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            if (length<10)
            {
                txtfax.setEditable(true);
            }
            else
            {
                txtfax.setEditable(false);
            }
        }
        else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                txtfax.setEditable(true);
            }
            else
            {
                txtfax.setEditable(false);
            }

        }
    }//GEN-LAST:event_txtfaxKeyPressed

    private void txtemailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyPressed
        // TODO add your handling code here:
        if(!txtemail.getText().isEmpty()){
            String regex = "^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z] {2,6}$";
            if(txtemail.getText().matches(regex)){
                product.setEmail(txtemail.getText());
            }
        }
    }//GEN-LAST:event_txtemailKeyPressed

    private void txtcontactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontactKeyReleased
        // TODO add your handling code here:
        String C1 = txtcontact.getText();
        if (C1.matches("^[0-9]*s")&& C1.length()==10);
    }//GEN-LAST:event_txtcontactKeyReleased

    private void txtcontactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontactKeyPressed
        // TODO add your handling code here:
        String contact = txtcontact.getText();
        int length = contact.length();

        char c = evt.getKeyChar();

        if (evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            if (length<10)
            {
                txtcontact.setEditable(true);
            }
            else
            {
                txtcontact.setEditable(false);
            }
        }
        else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                txtcontact.setEditable(true);
            }
            else
            {
                txtcontact.setEditable(false);
            }

        }
    }//GEN-LAST:event_txtcontactKeyPressed

    @SuppressWarnings("empty-statement")
    private void imgprvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_imgprvKeyPressed
        // TODO add your handling code here:
        imgprv.setIcon((product.getImg()));
        /*BufferedImage mypicture;
        if(CP.getImage() == null)
        {
          ;  
        }
        else
        {
            mypicture = ImageIO.read(CP.getImage());
            imgprv.setIcon(new ImageIcon(mypicture.getScaledInstance(110, 110, java.awt.Image.SCALE_SMOOTH)));
        }*/
    }//GEN-LAST:event_imgprvKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgprv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtaddress1;
    private javax.swing.JTextField txtaddress2;
    private javax.swing.JTextField txtban;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtdevice;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfax;
    private javax.swing.JTextField txthealth;
    private javax.swing.JTextField txtips;
    private javax.swing.JTextField txtlicense;
    private javax.swing.JTextField txtlinkedin;
    private javax.swing.JTextField txtmrn;
    private javax.swing.JTextField txtname;
    private javax.swing.JLabel txtphoto;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextPane txtuin;
    private javax.swing.JTextField txtvehicle;
    // End of variables declaration//GEN-END:variables

    private void displayproduct() {
        txtname.setText(product.getName());
        txtaddress.setText(product.getGeographicData());
        txtaddress1.setText(product.getGeographicData());
        txtaddress2.setText(product.getGeographicData());
        txtcontact.setText(String.valueOf(product.getTelephone()));
        txtdob.setText(String.valueOf(product.getDateofBirth()));
        txtfax.setText(String.valueOf(product.getFAX()));
        txtemail.setText(product.getEmail());
        txtssn.setText(String.valueOf(product.getSSN()));
        txtmrn.setText(product.getMedicalRecord());
        txthealth.setText(product.getHealthNumber());
        txtban.setText(String.valueOf(product.getBankAccount()));
        txtlicense.setText(String.valueOf(product.getLicenseNumber()));
        txtvehicle.setText(String.valueOf(product.getVehicleidentifier()));
        txtdevice.setText(String.valueOf(product.getDeviceidentifier()));
        txtlinkedin.setText(product.getLinkedin());
        txtips.setText(String.valueOf(product.getInternetprotocol()));
        txtuin.setText(String.valueOf(product.getUniqueidentifier()));
        
        
    
    }
}